model:
  decoder:
    vocab_size: 5000
    d_model: 512
    nhead: 8
    num_layers: 4
    dim_feedforward: 2048
    dropout: 0.05
    activation: swiglu
    positional_encoding: rope
    pad_token_id: 0
    bos_token_id: 1
    eos_token_id: 2
    max_length: 1024
  
  encoder:
    d_model: 512
    nhead: 8
    num_layers: 8
    dim_feedforward: 2048
    dropout: 0.05
    activation: "swiglu"
    max_length: 2048
    position_encoding_type: "rope"

    # CPWord: family, position, pitch, duration, program (instrument), tempo, time signature
    src_vocab_size_list: [3, 131, 130, 102, 131, 34, 66]
    src_embedding_size_list: [8, 64, 64, 64, 32, 32, 32]

    pad_token_id: 0
    bos_token_id: 1
    eos_token_id: 2

data:
  dataset_path: DATA/huggingface_seq2seq_rd
  split: training

  max_source_length: 1024
  max_target_length: 1024

  tokenizer_path: DATA/tokenizer_rd.json

  length_bucketing: true
  bucket_size_multiplier: 50

  num_workers: 4
  shuffle_seed: 42

  pad_token_id: 0
  bos_token_id: 1
  eos_token_id: 2

  curriculum_stage_prob: 
    - [1.0, 0.0, 0.0]
    - [0.25, 0.75, 0.0]
    - [0.2, 0.3, 0.5] 

training:
  # ===== pretrained decoder =====
  pretrained_decoder_path: DATA/pretrained_decoder/decoder_qkv_rope_best.pt

  # ===== batch & optimizer =====
  batch_size: 16
  accumulate_grad_batches: 8
  precision: bf16-mixed
  learning_rate: 0.0003
  weight_decay: 0.1
  grad_clip_norm: 1.0

  label_smoothing: 0.0

  # ===== scheduler =====
  scheduler: cosine
  warmup_steps: 400
  min_lr_ratio: 0.1

  # ===== training =====
  num_steps: null
  num_epochs: 1
  max_duration_seconds: 7000

  # ===== eval =====
  eval_every: 500
  num_eval_batches: 16

  early_stopping_patience: null
  early_stopping_min_delta: 0.0

  # ===== logging =====
  log_every: 100

  device: auto

  # ===== checkpoint =====
  save_checkpoint_path: artifacts/seq2seq/latest.pt
  save_best_checkpoint_path: artifacts/seq2seq/best.pt
  resume_checkpoint_path: null

  # ===== logs =====
  csv_log_path: logs/seq2seq.csv
  tensorboard_log_dir: logs/tensorboard/seq2seq

  # ===== LoRA strategy =====
  use_lora: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05

  # ===== Curriculum Scheduling =====
  curriculum_learning: true
  curriculum_epoch_schedule: [0, 3, 6]